FROM openjdk:8-jre-alpine

# Maintainer
MAINTAINER "akshat <akshat.mbx@gmail.com">

ENV SPRING_OUTPUT_ANSI_ENABLED=ALWAYS \
    JHIPSTER_SLEEP=0 \
    JAVA_OPTS=""

CMD echo "The application will start in ${JHIPSTER_SLEEP}s..." && \
    sleep ${JHIPSTER_SLEEP} && \
#    java ${JAVA_OPTS} -Djava.security.egd=file:/dev/./urandom -jar nrms-portal-2.0.0-SNAPSHOT.jar

	java ${JAVA_OPTS}-Djava.security.egd=file:/dev/./urandom -jar /app.war
	ADD codetestbackend-0.0.1-SNAPSHOT.jar /app.war
 
	EXPOSE 8080